=== ZakSir/HireMeProd/core/schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "https://hiremeprod.local/schema/resume",
  "required": false,
  "properties": {
    "candidate": {
      "type": "object",
      "id": "https://hiremeprod.local/schema/resume/candidate",
      "required": true,
      "properties": {
        "location": {
          "type": "string",
          "id": "https://hiremeprod.local/schema/resume/candidate/location",
          "required": true
        },
        "email": {
          "type": "string",
          "id": "https://hiremeprod.local/schema/resume/candidate/email",
          "required": true
        },
        "phone": {
          "type": "number",
          "id": "https://hiremeprod.local/schema/resume/candidate/phone",
          "required": true
        },
        "name": {
          "type": "object",
          "id": "https://hiremeprod.local/schema/resume/candidate/name",
          "required": true,
          "properties": {
            "givenName" : {
              "type": "string",
              "id": "https://hiremeprod.local/schema/resume/candidate/name/givenName",
              "required": true,
              "description": "The given name of the candidate"
            },
            "surname" : {
              "type": "string",
              "id" : "https://hiremeprod.local/schema/resume/candidate/name/surname",
              "required":true,
              "description": "The surname (last name) of the candidate"
            }
          }
        },
        "hobbies": {
          "type": "array",
          "id": "https://hiremeprod.local/schema/resume/candidate/hobbies",
          "required": true,
          "items": {
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/candidate/hobbies/0",
            "required": false
          }
        }
      }
    },
    "education": {
      "type": "object",
      "id": "https://hiremeprod.local/schema/resume/education",
      "required": false,
      "properties": {
        "degrees": {
          "type": "array",
          "id": "https://hiremeprod.local/schema/resume/education/degrees",
          "required": false
        },
        "highestDegreeObtained": {
          "type": "string",
          "id": "https://hiremeprod.local/schema/resume/education/highestDegreeObtained",
          "required": false
        }
      }
    },
    "experience": {
      "type": "array",
      "id": "https://hiremeprod.local/schema/resume/experience",
      "required": true,
      "items": {
        "type": "object",
        "id": "https://hiremeprod.local/schema/resume/experience/0",
        "required": false,
        "properties": {
          "dutiesAndAccomplishments": {
            "type": "array",
            "id": "https://hiremeprod.local/schema/resume/experience/0/dutiesAndAccomplishments",
            "required": true,
            "items": {
              "type": "string",
              "id": "https://hiremeprod.local/schema/resume/experience/0/dutiesAndAccomplishments/0",
              "required": false
            }
          },
          "endDate": {
            "type": "object",
            "id": "https://hiremeprod.local/schema/resume/experience/0/endDate",
            "required": true,
            "properties" : {
              "year" : {
                "type" : "number",
                "id" : "https://hiremeprod.local/schema/resume/experience/0/endDate/year",
                "required": true
              },
              "month" : {
                "type" : "number",
                "id" : "https://hiremeprod.local/schema/resume/experience/0/endDate/month",
                "required": true
              }
            }
          },
          "startDate": {
            "type": "object",
            "id": "https://hiremeprod.local/schema/resume/experience/0/startDate",
            "required": true,
            "properties" : {
              "year" : {
                "type" : "number",
                "id" : "https://hiremeprod.local/schema/resume/experience/0/startDate/year",
                "required": true
              },
              "month" : {
                "type" : "number",
                "id" : "https://hiremeprod.local/schema/resume/experience/0/startDate/month",
                "required": true
              }
            }
          },
          "title": {
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/experience/0/title",
            "required": true
          },          
          "team": {
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/experience/0/team",
            "required": true
          },          
          "company": {
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/experience/0/company",
            "required": true
          },
          "contractorTo":{
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/experience/0/contractorTo",
            "required" : false
          }
        }
      }
    },
    "objective": {
      "type": "string",
      "id": "https://hiremeprod.local/schema/resume/objective",
      "required": false
    },
    "proficiencies": {
      "type": "array",
      "id": "https://hiremeprod.local/schema/resume/proficiencies",
      "required": false,
      "items": {
        "type": "object",
        "id": "https://hiremeprod.local/schema/resume/proficiencies/0",
        "required": false,
        "properties": {
          "favoriteActivities": {
            "type": "array",
            "id": "https://hiremeprod.local/schema/resume/proficiencies/0/favoriteActivities",
            "required": false,
            "items": {
              "type": "string",
              "id": "https://hiremeprod.local/schema/resume/proficiencies/0/favoriteActivities/0",
              "required": false
            }
          },
          "level": {
            "type": "string",
            "id": "https://hiremeprod.local/schema/resume/proficiencies/0/level",
            "required": false
          },
          "skillName": {
            "type": "array",
            "id": "https://hiremeprod.local/schema/resume/proficiencies/0/skillName",
            "required": false,
            "items": {
              "type": "string",
              "id": "https://hiremeprod.local/schema/resume/proficiencies/0/skillName/0",
              "required": false
            }
          },
          "yearsOfExperience": {
            "type": "number",
            "id": "https://hiremeprod.local/schema/resume/proficiencies/0/yearsOfExperience",
            "required": false
          }
        }
      }
    }
  }
}

=== ZakSir/HireMeProd/usr/wife_unit/resume.json
{ 
  "$schema": "https://raw.githubusercontent.com/ZakSir/HireMe/master/resumeSchema.json",
  "candidate": {
    "name": {
      "givenName" :"Danni",
      "surname": "Fargo"
    },
     "email": "hiredannifargo@gmail.com",
    "phone": 4252688126,
    "hobbies": [
      "Welding (GMAW, GTAW)",
      "Borosilicate Flameworking",
      "Piano",
      "Winning"
    ],
    "location": "Renton, WA"
},
"proficiencies": [
    
],
"experience": [
    
],
"objective": "Winning! among other things and stuff."
}
